Remove unnecessary state and effect from HomePage
ucsb-cs156-s23/proj-happycows-s23-6pm-2 pull request #19
Opened 2023-06-01 18:04 UTC by chriscerie

This removes an unnecessary state and effect that's doing more harm than good. It causes out of sync state until the following render which can potentially be problematic for downstream consumers.

2023-06-01 20:15 UTC, jgarcia-ucsb approved these changes
Looks good to me based on this article: [https://react.dev/learn/you-might-not-need-an-effect](https://react.dev/learn/you-might-not-need-an-effect)

2023-06-02 18:38 UTC, pconrad requested changes
This looks right to me.

But I want to challenge you to up your game in terms of how you present this in the description.


 I think you are likely correct about the useEffect call 
 
But can you explain more about the "before and after" here?    You said that the problem this addresses is:
> This removes an unnecessary state and effect that's doing more harm than good.  It causes out of sync state until the following render which can potentially be problematic for downstream consumers.

Suppose that a product owner, or QA tester said: can you explain that to me without any technical jargon?
What would I experience as an end user before and after this change?
Or is the argument that there is no change for the end user, and you are just removing unnecessary code and complexity for the same end user experience?

2023-06-02 19:12 UTC, chriscerie commented
This removes an unnecessary render, but the impact is negligible. In this particular case if we left the code as it is, end users will not notice anything different as mentioned in the original description.

Rather it is a source of bug for future code that relies on synced state. It also serves a bad example for future authors, which we saw in #13 that used this same pattern.

2023-06-04 20:49 UTC, pconrad approved these changes
LGTM... will test on staff-qa

2023-06-04 20:59 UTC, merged