Fixed table overflow for profits table. Added a scroller when horizontal view is less than 1800px
ucsb-cs156-s23/proj-happycows-s23-6pm-2 pull request #38
Opened 2023-06-05 06:31 UTC by jgarcia-ucsb

Fixes [#24](https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/issues/24)

Modified the profits and profits table to prevent an overflow in the horizontal direction when the window is less than a certain size. Makes it easier for the user to read the table data. Added test-id's and an additional check in each test file in order to kill surviving mutants due to the div style. Also changed a stryker enable to a stryker restore, based on this post: [stryker slack](https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685726928710669)

Before:
<img width="292" alt="Screen Shot 2023-06-04 at 4 50 50 PM" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/assets/114465206/10f12209-849c-4c3e-9089-c3faae00158d">

After:
<img width="292" alt="Screen Shot 2023-06-04 at 4 51 14 PM" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/assets/114465206/2e792973-ac90-475d-a915-018521d43c6e">
<img width="292" alt="Screen Shot 2023-06-04 at 4 51 28 PM" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/assets/114465206/6276dbcb-3f4c-4f62-be5c-99280c37fcd9">
<img width="292" alt="Screen Shot 2023-06-04 at 4 51 45 PM" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/assets/114465206/5c1effe2-e2f8-4a75-8672-50c53e3fea32">

2023-06-05 15:57 UTC, chriscerie requested changes
Story: https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-2/prs/38/storybook/?path=/story/components-commons-profits--uncontrolled

2023-06-05 15:57 UTC, chriscerie commented on frontend/src/main/components/Commons/Profits.js
> +                </div>
This should just render `ProfitsTable` without a div container.

2023-06-05 17:10 UTC, chriscerie approved these changes
Thanks! This PR made me notice the 2 useMemo calls in `ProfitsTable.js` that are doing more harm than good both in terms of performance and complexity. It's not the optimization the author intended, but alas fixing it here is out of scope.

2023-06-08 02:35 UTC, pconrad approved these changes
LGTM

2023-06-08 02:35 UTC, merged